ruby/config/routes.rb
Rails.application.routes.draw do
  resources :profiles

  devise_for :users
  get 'home/Index'
get '/myprofile' => 'profiles#myprofile' 
  root :to => "home#Index"

end

ruby/app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

ruby/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_one:profile
end

ruby/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
# Prevent CSRF attacks by raising an exception.
# For APIs, you may want touse :null_session instead.protect_from_forgery with: :exception
def after_sign_in_path_for(resource)
"/myprofile"
end
end

ruby/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def Index

  end
end

ruby/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  respond_to :html
def myprofile
profile = Profile.find_by_user_id(current_user.id)
if profile.nil?
redirect_to "/profiles/new"
else
@user = User.find(current_user.id)
@profile = Profile.find_by_user_id(@user.id)
redirect_to "/profiles/#{@profile.id}"
end
end
  def index
    @profiles = Profile.all
    respond_with(@profiles)
  end

  def show
    respond_with(@profile)
  end

 # GET /profiles/new
def new
@user = User.find(current_user.id)
@profile = Profile.new
@profile.user_id = @user.id
end
  def edit
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.save
    respond_with(@profile)
  end

  def update
    @profile.update(profile_params)
    respond_with(@profile)
  end

  def destroy
    @profile.destroy
    respond_with(@profile)
  end

  private
    def set_profile
      @profile = Profile.find(params[:id])
    end

    def profile_params
      params.require(:profile).permit(:firstname, :lastname, :course, :studentno, :mobile, :user_id)
    end
end

ruby/app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
#after_sign_in_path_for is called by devise
def after_sign_in_path_for(user)
"/myprofile
" #adjust the returned path as needed
end
end

ruby/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby/app/helpers/home_helper.rb
module HomeHelper
end

ruby/app/helpers/profiles_helper.rb
module ProfilesHelper
end

ruby/app/helpers/sessions_controller_helper.rb
module SessionsControllerHelper
end

ruby/app/helpers/sessions_helper.rb
module SessionsHelper
end

ruby/app/views/home/Index.html.erb
<div class="center jumbotron">
  <h1>Welcome to the MathQuiz</h1>
  
    This is the home page for the
    
   <%= link_to "Sign up", new_user_session_path, class: "btn btn-lg btn-primary" %>
</div>

ruby/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Ruby MathQuiz" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    

    <%= javascript_include_tag "application" %>
	<link href="css/custom.css" rel="stylesheet">
	<link href="css/custom1.css" rel="stylesheet">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body class="full">

    <div class="navbar navbar-fixed-top navbar-inverse">>
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Ruby MathQuiz", '#', id: "logo" %>
       <!-- <a class="navbar-brand" href="#"></a> -->
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Sign in', new_user_session_path%></li>
            <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
            <li><%= link_to 'Register', new_user_registration_path  %></li>
          </ul>
        </div>
      </div>
    </div>

 
				<div class="form-body">
								
	<form id="banner-form" class="form" method="post">
	<%= bootstrap_flash %>
         <%= yield %>     				
	<p class="notice"><%= notice %></p>     
	<p class="alert"><%= alert %></p>
 	<% if user_signed_in? %>
	<div>Signed in as... <%= current_user.email %> (<%= link_to 'Sign out', destroy_user_session_path, :method => :delete%>)</div>
	<% else %>
<!--	<%= link_to 'Register', new_user_registration_path %> or <%= link_to 'Sign in', new_user_session_path %> -->
	<% end %>
        </div>
        </div>
        </div>
        
      </div><!--/row-->

    </div> <!-- /container -->

  </body>
</html>

ruby/app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :course %><br>
    <%= f.text_field :course %>
  </div>
  <div class="field">
    <%= f.label :studentno %><br>
    <%= f.text_field :studentno %>
  </div>
  <div class="field">
    <%= f.label :mobile %><br>
    <%= f.text_field :mobile %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ruby/app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

ruby/app/views/profiles/index.html.erb
<h1>Listing profiles</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Course</th>
      <th>Studentno</th>
      <th>Mobile</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.firstname %></td>
        <td><%= profile.lastname %></td>
        <td><%= profile.course %></td>
        <td><%= profile.studentno %></td>
        <td><%= profile.mobile %></td>
        <td><%= profile.user %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

ruby/app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

ruby/app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @profile.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @profile.lastname %>
</p>

<p>
  <strong>Course:</strong>
  <%= @profile.course %>
</p>

<p>
  <strong>Studentno:</strong>
  <%= @profile.studentno %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @profile.mobile %>
</p>

<p>
  <strong>User:</strong>
  <%= @profile.user %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>